version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db: